spring.application.name=FINALEXAM-1
server.port=8081
#database configuration 
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



#ai provider configuration
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=-u1JgAqwmopmtqy8
spring.ai.openai.chat.model=gemini-2.5-flash


